// Actual app event handlers with a minimal DOM and renderer shim, not a browser layout test.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'../world3d');
function harness(saved){
  const ids=new Map(),store=new Map(saved?[['archimedes-world3d-0.2',saved]]:[]),blobs=new Map(),downloads=[];let frame,clock=0;
  class E{
    constructor(tag='div'){this.tagName=tag;this.children=[];this.style={};this.className='';this.value='';this.checked=false;this.hidden=false;this.textContent='';this.files=[];this.attrs={};}
    get classList(){return {toggle:(k,b)=>{const set=new Set(this.className.split(' ').filter(Boolean));if(b??!set.has(k))set.add(k);else set.delete(k);this.className=[...set].join(' ');},contains:k=>this.className.split(' ').includes(k)};}
    append(...v){this.children.push(...v);v.forEach(x=>x.parent=this);}replaceChildren(...v){this.children=[];this.append(...v);}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);}
    addEventListener(k,fn){this['on'+k]=fn;}setAttribute(k,v){this.attrs[k]=v;}getBoundingClientRect(){return {width:600,height:400,left:0,top:0};}
    getContext(){return new Proxy({},{get:()=>()=>{},set:()=>true});}showModal(){this.open=true;}
    click(){if(this.tagName==='a')downloads.push({href:this.href,name:this.download});return this.onclick?.();}
  }
  const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  for(const m of html.matchAll(/<([a-z][\w-]*)\b([^>]*)>/gi)){const id=m[2].match(/\bid="([^"]+)"/);if(!id)continue;assert(!ids.has(id[1]),'Duplicate id');const el=new E(m[1]);el.value=m[2].match(/\bvalue="([^"]*)"/)?.[1]??'';el.hidden=/\bhidden\b/.test(m[2]);el.checked=/\bchecked\b/.test(m[2]);ids.set(id[1],el);}
  for(const m of html.matchAll(/<select\b[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)){const selected=m[2].match(/<option\b[^>]*value="([^"]+)"[^>]*selected/)||m[2].match(/<option\b[^>]*value="([^"]+)"/);ids.get(m[1]).value=selected[1];}
  const document={hidden:false,body:new E('body'),getElementById:id=>{assert(ids.has(id),'Missing id '+id);return ids.get(id);},createElement:t=>new E(t),createTextNode:text=>({textContent:text}),addEventListener(k,fn){this['on'+k]=fn;}};
  const c={document,console,Blob,performance:{now:()=>clock},devicePixelRatio:1,requestAnimationFrame:f=>{frame=f;},setTimeout:(f,delay)=>{if(delay<100)f();return 1;},addEventListener(){},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},URL:{createObjectURL:b=>{const id='blob:'+blobs.size;blobs.set(id,b);return id;},revokeObjectURL(){}}};c.window=c;vm.createContext(c);
  for(const f of['engine3d.js','controller.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);
  c.ArchimedesView={Renderer:class{setMode(mode){this.mode=mode;}draw(w){assert(w.agents.every(a=>a.p.every(Number.isFinite)));}project(){return null;}}};
  vm.runInContext(fs.readFileSync(path.join(root,'world.js'),'utf8'),c);
  return {el:id=>ids.get(id),click:id=>ids.get(id).click(),change:(id,v)=>{ids.get(id).value=v;return ids.get(id).onchange?.();},snapshot:()=>JSON.parse(JSON.stringify(c.ArchimedesWorldDebug.snapshot())),advance:ms=>{clock+=ms;frame(clock);},store,downloads,blobs,c};
}
test('3D UI initializes controls and advances only when asked',()=>{const h=harness();assert.equal(h.el('metric-c').textContent,'1.000');assert.equal(h.el('timeline').children.length,1);h.advance(200);assert.equal(h.snapshot().world.tick,0);h.click('run');h.advance(200);h.click('run');assert.equal(h.snapshot().world.tick,2);h.click('step');assert.equal(h.snapshot().world.tick,3);});
test('3D interventions and inspector bind to actual world state',()=>{const h=harness();h.click('probe');h.click('blackout');assert.equal(h.snapshot().world.probes.length,1);assert.equal(h.snapshot().world.blackout,80);h.click('agent-2');assert.equal(h.el('agent-name').textContent,'HYPATIA');h.change('action','recharge');h.change('coupling','0');assert.equal(h.snapshot().world.action,'recharge');assert.equal(h.snapshot().world.params.coupling,0);h.click('clear-probes');assert.equal(h.snapshot().world.probes.length,0);});
test('3D future buttons preview without changing live world and apply selected candidate',async()=>{const h=harness(),before=h.snapshot().world;await h.click('plan');assert.deepEqual(h.snapshot().world,before);const host=h.el('experiment-output'),cards=host.children[2];assert.equal(cards.children.length,3);cards.children[1].click();const action=cards.children[1].children[0].textContent.split(' → ')[0];h.el('experiment-output').children[3].children[0].click();assert.equal(h.snapshot().world.action,action);});
test('3D history restores state and preserves the current unsaved continuation',()=>{const h=harness();h.click('step');h.el('timeline').children[0].click();assert.equal(h.snapshot().world.tick,0);assert(h.snapshot().history.some(n=>n.label==='Before rewind'&&n.world.tick===1));h.click('pulse');assert.equal(h.snapshot().world.tick,0);});
test('3D downloads round-trip and rejected imports preserve current state',async()=>{const h=harness();h.click('step');h.click('export');const text=await h.blobs.get(h.downloads[0].href).text();assert.equal(JSON.parse(text).session.world.tick,1);h.click('step');const before=h.snapshot();h.el('file').files=[{size:2,text:async()=>'{}'}];await h.el('file').onchange();assert.deepEqual(h.snapshot(),before);assert.match(h.el('status').textContent,/Import rejected/);h.el('file').files=[{size:text.length,text:async()=>text}];await h.el('file').onchange();assert.equal(h.snapshot().world.tick,1);});
test('3D counterfactual and browser persistence retain exact state',async()=>{const h=harness();h.click('step');const before=h.snapshot().world;await h.click('counterfactual');assert.deepEqual(h.snapshot().world,before);assert.match(h.el('experiment-output').children[0].textContent,/Paired counterfactual/);h.click('snapshot');const restored=harness(h.store.get('archimedes-world3d-0.2'));assert.deepEqual(restored.snapshot(),h.snapshot());});
